name: Build & test

on:
  workflow_call:
    inputs:
      platform:
        required: true
        description: 'Platform to use for building'
        type: string
      dependencies-linux:
        description: 'List of dependencies to install on Linux'
        required: false
        type: string
      qt-version:
        description: 'Qt version to install'
        required: false
        type: string
        default: 6.5.*

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: Build & test
    runs-on: ${{ inputs.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies on Linux
        if: ${{ inputs.dependencies-linux }}
        run: sudo apt-get install -y ${{ inputs.dependencies-linux }}

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ inputs.qt-version }}
          modules: 'qt5compat'
      
      - name: Set CL=/MP environment variable on Windows 
        if: runner.os == 'Windows'
        run: echo "CL=/MP" >> $GITHUB_ENV

      - name: Configure CMake
        run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      - name: Build
        run: cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }} --parallel 4

      - name: Setup run env
        uses: przemek83/workflows/.github/actions/setup-qt-run-env@main

      - name: Used env vars
        run: |
          echo "CL: $CL" 
          echo "QT_QPA_PLATFORM: $QT_QPA_PLATFORM"
      
      - name: Run tests
        working-directory: ${{ github.workspace }}/build
        run: ctest -C ${{ env.BUILD_TYPE }} -E 'Benchmark'
